import type { Metadata } from "next";
import "./globals.css";
import { Children } from "@/types";
import { poppins } from "@/lib/fonts";
import AosProvider from "@/providers/AosProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: Children) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AosProvider>{children}</AosProvider>
        <Toaster position="top-center" expand={false} />
      </body>
    </html>
  );
};

export default MainLayout;
