import type { Metadata } from "next";
import "./globals.css";
import { IChildren } from "@/types";
import { poppins } from "@/lib/fonts";
import AosProvider from "@/providers/AosProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: IChildren) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AosProvider>{children}</AosProvider>
      </body>
    </html>
  );
};

export default MainLayout;
